### PR TITLE
Drop dependency on middleclass, and add docs folder

### PR DESCRIPTION
**Pull request by deepakjois**
I would like to use LuaLinkedList in my project, but I feel that the dependency on middleclass is not needed, and is a bit of an overkill.

Please consider merging this pull request, which:
- Drops the dependency on middleclass, and uses Lua primitives to enable class and object based operations.
- Adds a README and docs folder.

### CODE REVIEW

**Comment by deepakjois** [comment]
I have published the generated docs here: https://deepakjois.github.io/LuaLinkedList

You can also enable it after merging at: https://github.com/zunware/LuaLinkedList/settings (under Github pages)

**Comment by deepakjois** [comment]
Hello, just wanted to ping you.

If you are not interested in this patch or don’t have time to merge and release this, I am happy to just use LinkedList inside my own codebase.

**Comment by josellausas** [comment]
Sorry for the late reply. Thanks for the changes!

**Comment by deepakjois** [comment]
Thank you. For what it’s worth I used your library inside [luabidi](https://github.com/deepakjois/luabidi). I eventually decided to bundle the files in the project itself. But it’s nice to have the contributions merged in.

**Pull request merged**
